language: node_js
node_js:
  - "6"
  - "7"
services:
  - postgresql
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
  - TRAVIS=travis CXX=g++-4.8
script:
  - npm test && npm run coverage
