language: node_js
node_js:
  - "8"
services:
  - postgresql
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
  - TRAVIS=travis CXX=g++-4.8
before_script:
  - psql -c 'create database hapi_postgres_boilerplate_test;' -U postgres
script:
  - npm test && npm run coverage
